"""bhairava.reporting.html -- HTML report renderer."""
from __future__ import annotations
import html
from datetime import datetime, timezone
from ..findings.models import Finding


_SEV_COLOR = {
    "critical": "#b30000", "high": "#d9534f", "medium": "#f0ad4e",
    "low": "#5bc0de", "info": "#777",
}


def _h(s) -> str:
    return html.escape(str(s) if s is not None else "")


def render(findings: list[Finding], target: str = "", program: str = "") -> str:
    rows = []
    for f in sorted(findings,
                    key=lambda x: list(_SEV_COLOR).index(x.severity)
                    if x.severity in _SEV_COLOR else 99):
        color = _SEV_COLOR.get(f.severity, "#000")
        rows.append(f"""<tr>
<td><code>{_h(f.id)}</code></td>
<td>{_h(f.title)}</td>
<td style="color:{color};font-weight:bold">{_h(f.severity)}</td>
<td>{f.confidence:.2f}</td>
<td>{_h(f.status)}</td>
<td>{_h(f.url)}</td>
</tr>""")

    body_rows = "\n".join(rows) if rows else '<tr><td colspan="6"><em>no findings</em></td></tr>'

    return f"""<!doctype html>
<html><head><meta charset="utf-8"><title>BHAIRAVA-BB Report</title>
<style>
body{{font-family:-apple-system,Segoe UI,Roboto,sans-serif;margin:2em;max-width:1200px;color:#222}}
h1{{border-bottom:2px solid #333;padding-bottom:6px}}
table{{border-collapse:collapse;width:100%;margin:1em 0}}
th,td{{border:1px solid #ccc;padding:6px 10px;text-align:left;vertical-align:top}}
th{{background:#f4f4f4}}
</style></head><body>
<h1>BHAIRAVA-BB &mdash; Security Report</h1>
<p>
<b>Program:</b> {_h(program) or "&mdash;"}<br>
<b>Target:</b> {_h(target) or "&mdash;"}<br>
<b>Generated:</b> {datetime.now(timezone.utc).isoformat()}<br>
<b>Findings:</b> {len(findings)}
</p>
<h2>Findings</h2>
<table>
<tr><th>ID</th><th>Title</th><th>Severity</th><th>Confidence</th><th>Status</th><th>URL</th></tr>
{body_rows}
</table>
<hr><p><em>Generated by BHAIRAVA-BB v1.0.0 &mdash; authorized security research only.</em></p>
</body></html>"""
